[tool.black]
line-length = 100
target-version = ["py310", "py311", "py312"]
include = '\\.(py)$'
extend-exclude = '''
(
  ^/data/
  | ^/venv/
  | ^/.venv/
  | ^/env/
  | ^/.git/
  | ^/dist/
  | ^/build/
  | ^/colab_.*\.py
)
'''

[tool.isort]
profile = "black"
line_length = 100
force_single_line = false
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
skip = ["data", "venv", ".venv", "build", "dist", ".git"]
skip_glob = ["colab_*.py"]

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [
  "data",
  "venv",
  ".venv",
  "build",
  "dist",
  ".git",
  "colab_simple.py",
  "colab_standalone.py",
  "colab_train_simple.py",
]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
  "UP", # pyupgrade
]
ignore = [
  "E203",  # whitespace before ':' (black compatibility)
  "E266",  # too many leading '#' for block comment
  "E501",  # line length (handled by formatter)
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "auto"
