# Configuration for 20-model ensemble (5 folds x 4 encoders)
encoders: 
  - "resnet34"
  - "mobilenet_v2" 
  - "efficientnet_b0"
  - "efficientnet_b3"

folds: 5

# Override settings for ensemble
train:
  epochs: 20                           # Shorter per model
  early_stopping_patience: 6

# Ensemble inference settings
ensemble:
  vote_threshold: 0.3                  # Threshold for ensemble voting
  min_votes: 8                         # Min votes out of 20 models
  tta_per_model: false                 # TTA per model (expensive)
  final_tta: true                      # TTA on ensemble average
