# T4 GPU optimized config
seed: 42
project_name: "SlumSeg-T4"

data:
  root: "/kaggle/input/slum-detection"  # Kaggle dataset path
  images_dir: "images"
  masks_dir: "masks"
  tile_size: 512                        # Optimal for T4
  tile_overlap: 64
  train_regions_file: ""
  val_ratio: 0.15
  min_slum_px: 256                      # More permissive for T4 speed
  cache_dir: "/kaggle/working/cache"

augment:
  train:
    hflip: 0.5
    vflip: 0.3
    rotate_deg: 15
    brightness: 0.2
    contrast: 0.2
    blur: 0.15
    cutout_prob: 0.3
  valid: {}

model:
  arch: "unet"
  encoder: "efficientnet_b0"            # Fast on T4
  pretrained: true
  in_channels: 3
  classes: 1

loss:
  name: "bce_dice"
  pos_weight: null

train:
  epochs: 30
  batch_size: 24                        # Optimized for T4 16GB
  lr: 4e-4
  weight_decay: 1e-4
  scheduler: "onecycle"
  amp: true
  channels_last: true
  grad_ckpt: true
  compile_mode: "reduce-overhead"
  num_workers: 4                        # T4 has 4 vCPUs
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2
  accumulate_grad_batches: 1
  early_stopping_patience: 10

eval:
  threshold: 0.5
  tta: false

infer:
  tta: true
  threshold: 0.45
  num_samples: 20
  overlay_alpha: 0.4
  postprocess: true

hardware:
  cudnn_benchmark: true
  tf32: true
  deterministic: false
